
[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[pypi-dependencies]
NeoDynamics = { path = ".", editable = true }

[environments]
default = { solve-group = "default" }

[tasks]

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[dependencies]
python = "3.11.*"
openmmforcefields = ">=0.14.1,<0.15"
openff-toolkit = ">=0.16.9,<0.17"
