"""Docs configuration-reference sync tests (issue #17, track W0-b).

``docs/reference/configuration.md`` is GENERATED by
``docs/generate_reference.py`` from the live package. Discipline: the
generator only reads public neomd surface (``plan.KNOWN_KEYS``, the
registry vocabularies, ``CV_EXPRESSIONS``) and checks every documented
key through ``neomd.validate_config`` — and this test pins the committed
markdown to that generator:

1. the committed reference is byte-identical to a fresh regeneration
   through the generator's public entry (``generate``); regeneration also
   re-runs the generator's own drift self-checks,
2. the documented vocabularies match the live registry (every registered
   restraint / cv / method name — and nothing else — is rendered),
3. the documented top-level key table equals ``plan.KNOWN_KEYS``, and
   each of those keys is accepted by plan validation through the public
   interface (an unknown key IS flagged, a whitelisted one is not).
"""

import importlib.util
from pathlib import Path

import neomd
import neomd.colvars  # noqa: F401  (import = registration)
import neomd.methods  # noqa: F401  (import = registration)
import neomd.restraints  # noqa: F401  (import = registration)
from neomd.plan import KNOWN_KEYS
from neomd.registry import registered

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "docs" / "generate_reference.py"
COMMITTED = REPO_ROOT / "docs" / "reference" / "configuration.md"


def _load_generator():
    """Import the committed generator through its public module surface."""
    spec = importlib.util.spec_from_file_location(
        "neomd_docs_generate_reference", GENERATOR
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _committed_text() -> str:
    return COMMITTED.read_text(encoding="utf-8")


def test_committed_reference_is_in_sync(tmp_path):
    """generate() through its public entry reproduces the committed file."""
    module = _load_generator()
    rendered = module.generate(tmp_path / "configuration.md")
    committed = _committed_text()
    # the temp-path write and the return value agree, and both equal the
    # committed file — no drift between generation and what is committed
    assert rendered == committed
    assert (tmp_path / "configuration.md").read_text(encoding="utf-8") == committed


def test_reference_covers_exactly_the_registry_vocabularies():
    """Every registry entry — and only registry entries — is documented."""
    text = _committed_text()
    for name in registered("restraint"):
        assert f"### `type: {name}`" in text, f"restraint {name} not documented"
    for name in registered("cv"):
        assert f"#### `{name}`" in text, f"cv {name} not documented"
    for name in registered("method"):
        assert f"### `method: {name}`" in text, f"method {name} not documented"
    # and nothing extra: the rendered counts match the live registry sizes
    assert text.count("\n### `type: ") == len(registered("restraint"))
    assert text.count("\n#### `") == len(registered("cv"))
    assert text.count("\n### `method: ") == len(registered("method"))


def test_top_level_table_equals_known_keys():
    """The 'Top-level plan keys' table is exactly plan.KNOWN_KEYS."""
    text = _committed_text()
    section = text.split("## Top-level plan keys", 1)[1]
    section = section.split("\n### ", 1)[0]
    documented = {
        line.split("|")[1].strip().strip("`")
        for line in section.splitlines()
        if line.startswith("| `")
    }
    assert documented == set(KNOWN_KEYS)


def test_documented_top_level_keys_are_accepted_by_validation():
    """Keys claimed valid pass through neomd.validate_config's whitelist."""
    base = {
        "input_files": {"complex": "c.pdbx", "system": "s.xml"},
        "output": {"output_dir": "/tmp/neomd-docs-reference-test"},
    }

    def unknown(plan):
        return [e for e in neomd.validate_config(plan) if "unknown" in str(e)]

    # sanity of the probe itself: an unknown key IS reported as unknown
    probe = unknown({**base, "definitely_not_a_key": 1})
    assert any("definitely_not_a_key" in str(e) for e in probe)

    for key in sorted(KNOWN_KEYS):
        # values are deliberately junk (an empty mapping cannot satisfy
        # every section) — the assertion is only that validation does NOT
        # flag the KEY itself as unknown
        flagged = [e for e in unknown({**base, key: {}}) if key in str(e)]
        assert not flagged, f"documented top-level key {key!r} rejected as unknown"
